id: P3F4DA324
initial_creation_type: input
source_metadata:
  title: Kashmiri Śākyaśrībhadra
  language: es
  description: 'Texts by and about the Kashmiri master Śākyaśrībhadra (shā kya shrī
    bzang po, 1127–1225), who in 1204 travelled to Tibet, where he became the teacher
    of a number of important lamas, including Sakya Paṇḍita Kunga Gyaltsen:'
  volume:
    70169ad172314aae9764133b458c4640:
      title: An Instruction on Pure View and Conduct
      parent: Instructions
    80406624b80043eebfe7212119a04710:
      title: A Brief Practice for Paying Homage and Making Offerings to the Buddha
        together with his retinue of Arhats
      parent: Practices
    380bba15b7324d279d87162e1268bddb:
      title: Taking the Vows of Sojong
      parent: Practices
    44e5abaaac094e9b84d42d3320ca3dfd:
      title: The Seven Branches for Practising the Sacred Dharma
      parent: Practices
    6146d3e2bfbb4174b46a3984a07c33d6:
      title: Verses of Refuge and Bodhicitta
      parent: Practices
created_at: '2022-03-01T02:21:09.311285'
last_modified_at: '2022-03-01T02:21:09.311287'
